default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: admin_park_development

test:
  <<: *default
  database: admin_park_test

production:
  <<: *default
  database: admin_park_production
  username: admin_park
  password: <%= ENV['ADMIN_PARK_DATABASE_PASSWORD'] %>
